# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Installing nvm and Node.js..."
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
      source ~/.bashrc
      nvm install 16.20.2
      nvm alias default 16.20.2
      nvm use 16.20.2
      echo "Node.js version after changing:"
      node -v
      echo "Installing project dependencies..."
      npm install
      echo "Installing Angular CLI globally..."
      npm install -g @angular/cli
      echo "Installing Cypress..."
      npx cypress install
    command: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
      nvm use 16.20.2
      echo "Using Node.js version:"
      node -v
      npm start

  - name: Run Tests
    before: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
      nvm use 16.20.2
      echo "Using Node.js version for tests:"
      node -v
      npm install
    command: npm run test

  - name: install cypress to workspace
    init: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
        nvm use 16.20.2
        npx cypress install

  - name: run chrome tests
    command: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
        nvm use 16.20.2
        yes | npx cypress run --browser chrome

  - name: open cypress application
    command: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
        nvm use 16.20.2
        yes | npx cypress open

ports:
  - port: 4200
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
